apiVersion: v1
kind: ConfigMap
metadata:
  name: uniearn-api-config
  namespace: dev
data:
  DEPLOYMENT_ENV: dev


---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: uniearn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniearn-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: uniearn-api
    spec:
      containers:
        - name: uniearn-api
          image: __IMAGE__
          args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
          resources:
            limits:
              cpu: 800m
              memory: 1500Mi
            requests:
              cpu: 300m
              memory: 1000Mi
          env:
            - name: DEPLOYMENT_ENV_KEY
              valueFrom:
                configMapKeyRef:
                  name: uniearn-api-config
                  key: DEPLOYMENT_ENV
          envFrom:
            - configMapRef:
                name: uniearn-api-config


---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: uniearn-api
spec:
  ports:
    - port: 9334
  selector:
    app: uniearn-api
  type: NodePort